# cat karpenter-nodepools.yaml 
# This example NodePool will provision general purpose instances
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: lcsc-wm-fat-nodepool-graviton-v1
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  limits:
    cpu: "128"
    memory: "256Gi"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  template:
    spec:
      expireAfter: Never 
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["c7g"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["4xlarge"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose EC2NodeClass for running Amazon Linux 2 nodes"
spec:
  role: "KarpenterNodeRole-lcsc-wm-fat" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: lcsc-wm-fat # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/lcsc-wm-fat: owned # replace with your cluster name
  amiSelectorTerms:
    - alias: al2023@latest # Amazon Linux 2023